<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AlbumsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $albums = [
            [
                'title' => '1989',
                'artist' => 'Taylor Swift',
                'release_year' => 2014,
                'cover_image' => 'https://upload.wikimedia.org/wikipedia/en/f/f6/Taylor_Swift_-_1989.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Red (Taylor\'s Version)',
                'artist' => 'Taylor Swift',
                'release_year' => 2012,
                'cover_image' => 'https://pbs.twimg.com/media/FG8SDi1VEAcNGOb?format=jpg&name=4096x4096',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Lover',
                'artist' => 'Taylor Swift',
                'release_year' => 2019,
                'cover_image' => 'https://pbs.twimg.com/media/FyRf4ZDaAAAzB9S?format=jpg&name=900x900',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Fearless (Taylor\'s Version)',
                'artist' => 'Taylor Swift',
                'release_year' => 2008,
                'cover_image' => 'https://people.com/thmb/3t7qFSHbnwT6-fiMxa7FPzu6Liw=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():focal(1109x674:1111x676):format(webp)/taylor-swift-b2da7a6ca64744cd9ea0b35bdbe1e2cc.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Speak Now (Taylor\'s Version)',
                'artist' => 'Taylor Swift',
                'release_year' => 2008,
                'cover_image' => 'https://pbs.twimg.com/media/FvarZkpaYAglwlO?format=jpg&name=small',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Reputation',
                'artist' => 'Taylor Swift',
                'release_year' => 2017,
                'cover_image' => 'https://pbs.twimg.com/media/FzV8_w4XwAAVuAY?format=jpg&name=900x900',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Evermore',
                'artist' => 'Taylor Swift',
                'release_year' => 2020,
                'cover_image' => 'https://pbs.twimg.com/media/FzaZbsWXsAMYxjN?format=jpg&name=small',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Folklore',
                'artist' => 'Taylor Swift',
                'release_year' => 2020,
                'cover_image' => 'https://upload.wikimedia.org/wikipedia/pt/f/f8/Taylor_Swift_-_Folklore.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Positions',
                'artist' => 'Ariana Grande',
                'release_year' => 2020,
                'cover_image' => 'https://upload.wikimedia.org/wikipedia/pt/8/89/Positions_de_Ariana_Grande.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Sweetener',
                'artist' => 'Ariana Grande',
                'release_year' => 2018,
                'cover_image' => 'https://upload.wikimedia.org/wikipedia/en/7/7a/Sweetener_album_cover.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Thank U, Next',
                'artist' => 'Ariana Grande',
                'release_year' => 2019,
                'cover_image' => 'https://upload.wikimedia.org/wikipedia/en/thumb/d/dd/Thank_U%2C_Next_album_cover.png/220px-Thank_U%2C_Next_album_cover.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Twenty One Pilots',
                'artist' => 'Twenty One Pilots',
                'release_year' => 2009,
                'cover_image' => 'https://th.bing.com/th/id/R.68c47b17f86c36911a9387fd75110e44?rik=vuGdooFamPiyHA&riu=http%3a%2f%2fvignette1.wikia.nocookie.net%2ftwenty-one-pilots%2fimages%2f1%2f1a%2fTwenty_One_Pilots_album.png%2frevision%2flatest%3fcb%3d20160427085922&ehk=uSmlXnXXwxu8VtlXzuORQtMZIx0LR%2b%2fUpi24ZBGVp4Y%3d&risl=&pid=ImgRaw&r=0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Regional at Best',
                'artist' => 'Twenty One Pilots',
                'release_year' => 2011,
                'cover_image' => 'https://th.bing.com/th/id/R.55d878693f5de1f6d5a326d6d4712652?rik=HcYNTJiBjKOkTQ&pid=ImgRaw&r=0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Vessel',
                'artist' => 'Twenty One Pilots',
                'release_year' => 2013,
                'cover_image' => 'https://th.bing.com/th/id/OIP.nNMCYp1OSUijPR1aLzbRSwHaHY?pid=ImgDet&rs=1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Blurryface',
                'artist' => 'Twenty One Pilots',
                'release_year' => 2015,
                'cover_image' => 'https://th.bing.com/th/id/R.66fb8eb2019419e297152c7b38397d46?rik=Dt3IWuJ%2f4TT33A&pid=ImgRaw&r=0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Trench',
                'artist' => 'Twenty One Pilots',
                'release_year' => 2018,
                'cover_image' => 'https://images-na.ssl-images-amazon.com/images/I/81ucF7MxoeL._SL1441_.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Scaled and Icy',
                'artist' => 'Twenty One Pilots',
                'release_year' => 2021,
                'cover_image' => 'https://th.bing.com/th/id/R.0df7e90fce8b5d68af0636f7b47b07d2?rik=9fAQgy4gLNd2Jw&pid=ImgRaw&r=0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Los ángeles',
                'artist' => 'Rosalía',
                'release_year' => 2017,
                'cover_image' => 'https://th.bing.com/th/id/OIP.Ua_yFFZ7X85F9gwm427wCgHaHa?pid=ImgDet&rs=1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'El mal querer',
                'artist' => 'Rosalía',
                'release_year' => 2018,
                'cover_image' => 'https://th.bing.com/th/id/R.0e798c45cf3b4067820787404847a00e?rik=92p311m%2fHn9wrw&riu=http%3a%2f%2f5b0988e595225.cdn.sohucs.com%2fimages%2f20200324%2ff29cef5436114d10b3d6b42e0e227141.jpeg&ehk=QB72%2bXjeutzxglUgUhUgDMkbe07yYgGbzZah0CXP%2fEI%3d&risl=&pid=ImgRaw&r=0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Motomami',
                'artist' => 'Rosalía',
                'release_year' => 2021,
                'cover_image' => 'https://monkeybuzz.com.br/wp-content/uploads/2022/04/rosalia.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Days Are Gone',
                'artist' => 'HAIM',
                'release_year' => 2013,
                'cover_image' => 'https://monkeybuzz.com.br/wp-content/uploads/2013/09/haim-days-are-gone.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Something to Tell You',
                'artist' => 'HAIM',
                'release_year' => 2017,
                'cover_image' => 'https://m.media-amazon.com/images/I/81ztd0tQfeL._UF1000,1000_QL80_.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Women in Music Pt. III',
                'artist' => 'HAIM',
                'release_year' => 2020,
                'cover_image' => 'https://monkeybuzz.com.br/wp-content/uploads/2020/06/women-in-music-pt-iii.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Pure Heroine',
                'artist' => 'Lorde',
                'release_year' => 2013,
                'cover_image' => 'https://upload.wikimedia.org/wikipedia/commons/f/fe/Lorde_Pure_Heroine.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Melodrama',
                'artist' => 'Lorde',
                'release_year' => 2017,
                'cover_image' => 'https://upload.wikimedia.org/wikipedia/pt/b/b2/Lorde_-_Melodrama.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Artangels',
                'artist' => 'Grimes',
                'release_year' => 2015,
                'cover_image' => 'https://pbs.twimg.com/media/CRsEmWxUYAAob4j?format=jpg&name=4096x4096',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Miss Anthropocene',
                'artist' => 'Grimes',
                'release_year' => 2020,
                'cover_image' => 'https://cdns-images.dzcdn.net/images/cover/b069393ca5d13fea704e59d548d2c46d/500x500.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Mr. Morale & the Big Steppers',
                'artist' => 'Kendrick Lamar',
                'release_year' => 2021,
                'cover_image' => 'https://m.media-amazon.com/images/I/81JWgCwbohL._UF1000,1000_QL80_.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Rennaisance',
                'artist' => 'Beyoncé',
                'release_year' => 2022,
                'cover_image' => 'https://upload.wikimedia.org/wikipedia/pt/9/9d/Renaissance_-_Beyonc%C3%A9.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'I Disagree',
                'artist' => 'Poppy',
                'release_year' => 2020,
                'cover_image' => 'https://upload.wikimedia.org/wikipedia/en/e/e2/I_Disagree_Poppy.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?',
                'artist' => 'Billie Eilish',
                'release_year' => 2019,
                'cover_image' => 'https://upload.wikimedia.org/wikipedia/en/3/38/When_We_All_Fall_Asleep%2C_Where_Do_We_Go%3F.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Happier Than Ever',
                'artist' => 'Billie Eilish',
                'release_year' => 2021,
                'cover_image' => 'https://upload.wikimedia.org/wikipedia/pt/e/e8/Happier_Than_Ever_%28%C3%A1lbum%29_-_Billie_Eilish.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Queen of the Clouds',
                'artist' => 'Tove Lo',
                'release_year' => 2014,
                'cover_image' => 'https://upload.wikimedia.org/wikipedia/pt/5/57/Capa_de_Queen_of_the_Clouds.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Lady Wood',
                'artist' => 'Tove Lo',
                'release_year' => 2016,
                'cover_image' => 'https://upload.wikimedia.org/wikipedia/pt/f/fd/Tove_Lo_-_Lady_Wood.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Sunshine Kitty',
                'artist' => 'Tove Lo',
                'release_year' => 2019,
                'cover_image' => 'https://upload.wikimedia.org/wikipedia/pt/thumb/5/54/Sunshine_Kitty.png/220px-Sunshine_Kitty.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'The Family Jewels',
                'artist' => 'MARINA and the Diamonds',
                'release_year' => 2010,
                'cover_image' => 'https://i.scdn.co/image/ab67616d0000b2735e586c9004ed2100d5a20427',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Electra Heart',
                'artist' => 'MARINA and the Diamonds',
                'release_year' => 2012,
                'cover_image' => 'https://upload.wikimedia.org/wikipedia/en/8/81/Marina_and_the_Diamonds_-_Electra_Heart.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Born to Die',
                'artist' => 'Lana Del Rey',
                'release_year' => 2012,
                'cover_image' => 'https://upload.wikimedia.org/wikipedia/pt/4/47/LanaDelRey_BornToDie.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Paradise',
                'artist' => 'Lana Del Rey',
                'release_year' => 2012,
                'cover_image' => 'https://m.media-amazon.com/images/I/51oHVPxaiDL._UF1000,1000_QL80_.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Ultraviolence',
                'artist' => 'Lana Del Rey',
                'release_year' => 2014,
                'cover_image' => 'https://upload.wikimedia.org/wikipedia/pt/7/74/Ultraviolence.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Honeymoon',
                'artist' => 'Lana Del Rey',
                'release_year' => 2015,
                'cover_image' => 'https://monkeybuzz.com.br/wp-content/uploads/2015/09/528666-560bb2e921def.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Lust for Life',
                'artist' => 'Lana Del Rey',
                'release_year' => 2017,
                'cover_image' => 'https://upload.wikimedia.org/wikipedia/pt/c/cd/Lust_for_Life_-_Lana_Del_Rey.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Norman Fucking Rockwell!',
                'artist' => 'Lana Del Rey',
                'release_year' => 2019,
                'cover_image' => 'https://upload.wikimedia.org/wikipedia/pt/2/2f/NFR_Lana.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        DB::table('albums')->insert($albums);
    }
}
